---
title: "pckge_testing"
author: "Ryan Kopper"
date: "August 2, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, in clude=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# To read in data use rgdal::readOGR or sf::st_read

farmers2 <- readOGR("C:/Users/rkopp/Desktop/R_work/Cost_Distance_R/Decha_Transect_Points/Decha_Transect_Points.shp")

# or

farmers <- st_read("C:/Users/rkopp/Desktop/R_work/Cost_Distance_R/Decha_Transect_Points/Decha_Transect_Points.shp")



```



```{r}
#Load in the roads file from open street map that was converted to a raster in ARC


arc_roads <- "C:/Users/rkopp/Desktop/R_work/Cost_Distance_R/os_roads_contents/OS_Roads_ras1.tif"
arc_roads1 <- raster(arc_roads)
plot(arc_roads1)
plot_noaxes(arc_roads1)


#check coordinate reference system (EPSG: 4326)
st_crs(arc_roads1)


#Crop roads raster layer to the extent of Decha (and surrounding woredas  )
cropped_ar_rds <- crop(x = arc_roads1 ,
                  extent(35.49, 36.5, 6.22, 7.56))
plot_noaxes(cropped_ar_rds)
plot(Dech_crop, add = TRUE)

#------------------------------------------------------------------------------

#Looking to improve the resolution of the roads layer
res(cropped_ar_rds) # 0.05257174 0.05257174

#------------------------------------------------------------------------------
# #Use aggregate and a assign a factor to aggregate from
# 
# 
# rds.aggregate <- disaggregate(cropped_ar_rds, fact = 12)
# res(rds.aggregate)
# plot(rds.aggregate)
# #Doesn't improve much
#-------------------------------------------------------------------------------
# resampleFactor <- .5  # reduce the cell size by 50% and double the number of rows and columns.      
#      
# # inCols <- ncol(cropped_ar_rds)
# # inRows <- nrow(cropped_ar_rds)
# # resampledRaster <- raster(ncol=(inCols / resampleFactor), nrow=(inRows / resampleFactor))
# # extent(resampledRaster) <- extent(cropped_ar_rds)
# # resampledRaster <- resample(cropped_ar_rds, resampledRaster,datatype="INT1U",method='bilinear',filename="testOutResamp.tif",overwrite=TRUE)
# # plot(resampledRaster)
#-----------------------------------------------------------------------------

#Load in districts/Decha
districts <- readRDS("C:/Users/rkopp/Desktop/R_work/Buna/gadm36_ETH_2_sp.rds")

plot(districts)


#Organize .shp files
sfdat <- list("districts" = districts,  "roads" = roads, "farmers" = farmers)
sapply(sfdat, function(x) st_bbox(x))

#Show that they are in the same CRS (Cordinate reference system )
st_crs(districts)
st_crs(roads)
st_crs(farmers)

par(mar = c(0, 0, 0, 0))
plot(sfdat$districts %>% st_geometry(), col = "grey")
plot(sfdat$roads %>% st_geometry(), col = "red", add = TRUE)
plot(sfdat$farmers %>% st_geometry(), col = "blue", pch = 20, add = TRUE)

#Just DECHA w/ farmers, roads, DEM added in
par(mar = c(0, 0, 0, 0))
sel_Decha <- districts$NAME_3 == "Decha"
plot(districts[ sel_Decha, ], col = "yellow")
plot(districts, add = TRUE)
plot(sfdat$roads %>% st_geometry(), col = "red", add = TRUE)
plot(sfdat$farmers %>% st_geometry(), col = "blue", pch = 20, add = TRUE)





```


#Add DEMs to map and make sure CRS line up
```{r}

Keffa_DEM <- st_read("C:/Users/rkopp/Desktop/R_work/Buna/srtm/srtm_44_11.tif")
library(sf)

MA_DEM <- "C:/Users/rkopp/Desktop/R_work/MA_dem/srtm_22_04.tif"
r3 <- raster(MA_DEM)
mapview(r3)

library(raster)
fn <- "C:/Users/rkopp/Desktop/R_work/Buna/srtm/srtm_44_11.tif"
r1 <- raster(fn)
plot(r1)



st_crs(r1) #same crs as other files*


#PLOT EACH LAYER
par(mar = c(0, 0, 0, 0))
plot(districts[ sel_Decha, ])
plot(r1, add = TRUE)
plot(districts[ sel_Decha, ], add = TRUE)
plot(sfdat$roads %>% st_geometry(), col = "red", add = TRUE)
plot(sfdat$farmers %>% st_geometry(), col = "blue", pch = 20, add = TRUE)

```


#Now attempt to use gdistance
```{r}
library(gdistance)



```

Using the "mapview" package tomake map interactivewith layers
```{r}

library(mapview)
mapview(districts[ sel_Decha, ])
mapview(pts, add = TRUE) %>% plot(roads, add = TRUE)


library(dplyr)


```


